### ISSUE TITLE
Inquiry About Support for Android Studio Ladybug | 2024.2.1 Patch 3

### ISSUE THREAD

**Issue by VergilWu** [ozontech/kelp#7]
Hello,
I hope this message finds you well. I am writing to inquire about your development plans regarding support for the latest version of Android Studio, specifically Ladybug | 2024.2.1 Patch 3.
As a user of your plugin, I am eager to know if there are any upcoming updates or compatibility patches that will ensure seamless integration with this version of Android Studio. Your tool has been invaluable in my development workflow, and continued support would be greatly appreciated.
Thank you for your time and dedication to maintaining such a useful tool.

**Comment by popovanton0** [comment]
https://github.com/ozontech/kelp/releases/tag/v1.1.0
